openapi: 3.0.0
info:
  title: API de Gestion des Enseignants
  version: 1.0.0
paths:
  /teachers:
    post:
      summary: Ajouter un nouvel enseignant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Teacher"
      responses:
        '201':
          description: Enseignant ajouté avec succès
    get:
      summary: Récupérer la liste des enseignants
      responses:
        '200':
          description: Liste des enseignants récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Teacher"
  /teachers/{id}:
    get:
      summary: Récupérer un enseignant par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Enseignant récupéré avec succès
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Teacher"
    put:
      summary: Mettre à jour un enseignant par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Teacher"
      responses:
        '200':
          description: Enseignant mis à jour avec succès
    delete:
      summary: Supprimer un enseignant par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Enseignant supprimé avec succès
components:
  schemas:
    Teacher:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        courses:
          type: array
          items:
            type: object
            properties:
              course_name:
                type: string
              course_code:
                type: string
              course_duration:
                type: string


    New_teacher : 
      type: object
      properties:
        id:
          type: integer
          example: 1
        first_name:
          type: string
          example : Ryan
        last_name:
          type: string
          example: Andriamahery
        courses:
          type: array
          items:
            type: object
            properties:
              course_name: 
                type: string
                example: API
              course_code:
                type: string
                example: API
              course_duration: 
                type: string
                example: 120mn
               